  name: Build & Deploy Remind-me app

  on:
    push:
      branches:
        - ci_cd

  jobs:
    build:
      name: Build Remind-me
      runs-on: ubuntu-latest

      env:
        DB_DATABASE: test_db
        DB_USER: root
        DB_PASSWORD: root
        
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: '17'

        - name: Start MySQL
            run: |
              sudo /etc/init.d/mysql start
              mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

        - name: Unit Tests
          run: mvn -B test --file pom.xml

        - name: Build the app
          run: |
            mvn clean
            mvn -B package --file pom.xml


