  name: Build & Deploy Remind-me app

  on:
    push:
      branches:
        - ci_cd

  jobs:
    build:
      name: Build Remind-me
      runs-on: ubuntu-latest

      env:
        DB_NAME: remindme
        DB_USER: root
        DB_PASSWORD: root
        
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: 'corretto'
            java-version: '17'

        - name: Start MySQL
          run: |
            sudo /etc/init.d/mysql start
            mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USER -p$DB_PASSWORD
        
        - name: Unit Tests
          run: mvn -B test --file pom.xml

        - name: Build the app
          run: |
            mvn clean
            mvn -B package -DskipTests --file pom.xml

        - name: Build Docker Image
          run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/remind-me:latest .
#          uses: docker/build-push-action@v6
#          with:
#            context: .
#            dockerfile: Dockerfile
#            push: false
#            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/remind-me:latest

        - name: Login to Docker Hub
          env:
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
            DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          run: echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username $DOCKER_HUB_USERNAME --password-stdin
#          uses: docker/login-action@v3
#          with:
#            username: ${{ secrets.DOCKER_HUB_USERNAME }}
#            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Push to Docker Hub
          run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/remind-me:latest
#          uses: docker/build-push-action@v6
#          with:
#            context: .
#            dockerfile: Dockerfile
#            push: true
#            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/remind-me:latest
